In [1]:
import numpy as np

In [3]:
a = np.arange(24)
b = a.reshape(-1, 3, 4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [4]:
c = b.transpose((2, 0, 1))
c

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [12]:
a = np.arange(6).reshape((2, 3))
b = np.arange(10, 16).reshape((2, 3))
print(a)
print(b)
print()
c = np.concatenate((a, b))
print(c)
print()
c = np.concatenate((a, b), axis=-1)
print(c)


[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]

[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]

[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]


In [16]:
c = np.stack((a,b))
print(c)
print()
c = np.stack((a, b), axis=-1)
print(c)
print()

[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]]

[[[ 0 10]
  [ 1 11]
  [ 2 12]]

 [[ 3 13]
  [ 4 14]
  [ 5 15]]]

